# Generated by Django 5.2.11 on 2026-03-05 15:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="name_my",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
