# Generated by Django 5.2.11 on 2026-03-17 12:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0002_product_name_my"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="wholesale_price",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="stockmovement",
            name="created_at",
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="stockmovement",
            name="ref_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("SUP_INV", "Supplier Invoice"),
                    ("CUS_INV", "Customer Invoice"),
                    ("SUP_REQ", "Supplier Requisition"),
                    ("CUS_REQ", "Customer Requisition"),
                    ("RET_PART", "Stock Partition for Retail"),
                    ("RET_RETURN", "Return from Retail"),
                    ("ADJ", "Adjustment"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="WholesaleMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "movement_type",
                    models.CharField(
                        choices=[("IN", "Stock In"), ("OUT", "Stock Out")], max_length=3
                    ),
                ),
                ("unit_price", models.IntegerField(default=0)),
                ("quantity", models.PositiveIntegerField()),
                (
                    "ref_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("SUP_INV", "Supplier Invoice"),
                            ("CUS_INV", "Customer Invoice"),
                            ("SUP_REQ", "Supplier Requisition"),
                            ("CUS_REQ", "Customer Requisition"),
                            ("RET_PART", "Stock Partition for Retail"),
                            ("RET_RETURN", "Return from Retail"),
                            ("ADJ", "Adjustment"),
                        ],
                        max_length=20,
                    ),
                ),
                ("ref_no", models.CharField(blank=True, max_length=50)),
                ("remark", models.CharField(blank=True, max_length=255)),
                (
                    "created_at",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="store.product"
                    ),
                ),
            ],
        ),
    ]
