
"""
Django settings for chuefamily project.

Generated by 'django-admin startproject' using Django 5.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path
from django.contrib.messages import constants as messages


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# In production you MUST set SECRET_KEY in the environment.
SECRET_KEY = os.getenv("SECRET_KEY")

# Allow local development to run without setting SECRET_KEY.
# Production safety: if DEBUG is False and SECRET_KEY is missing, crash on startup.
if not SECRET_KEY:
    if os.getenv("DEBUG", "True").lower() in ("1", "true", "yes", "y", "on"):
        # A deterministic-but-not-secret dev key (OK for local only).
        SECRET_KEY = "django-insecure-local-dev-key-change-me"
    else:
        raise RuntimeError("SECRET_KEY environment variable is not set")

# SECURITY WARNING: don't run with debug turned on in production!
# Local default is True; set DEBUG=0/False on the server.
DEBUG = os.getenv("DEBUG", "True").lower() in ("1", "true", "yes", "y", "on")

ALLOWED_HOSTS = [h.strip() for h in os.getenv("ALLOWED_HOSTS", "*").split(",") if h.strip()]

# Helpful defaults for local development
if DEBUG:
    for _h in ("localhost", "127.0.0.1", "0.0.0.0"):
        if _h not in ALLOWED_HOSTS:
            ALLOWED_HOSTS.append(_h)

# CSRF: allow your Seenode domain(s) to POST to Django (admin login is a POST).
# You can override/add origins via env var CSRF_TRUSTED_ORIGINS as a comma-separated list.
_csrf_env = os.getenv("CSRF_TRUSTED_ORIGINS", "").strip()
CSRF_TRUSTED_ORIGINS = [
    # Seenode default domains (wildcards are supported by Django)
    "https://*.apps.run-on-seenode.com",
    "https://*.run-on-seenode.com",
    # Your current default domain (keep this even if wildcard should cover it)
    "https://web-3jaowsngtrt0.up-de-fra1-k8s-1.apps.run-on-seenode.com",
]
if _csrf_env:
    CSRF_TRUSTED_ORIGINS += [o.strip() for o in _csrf_env.split(",") if o.strip()]

# Local dev origins
if DEBUG:
    CSRF_TRUSTED_ORIGINS += [
        "http://127.0.0.1:8000",
        "http://localhost:8000",
    ]

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    'django.contrib.humanize', # Add this line
    "storages",
    "qrcode",
    "warehouse",
    "category",
    "accounts",
    "store",
    
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.locale.LocaleMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    
]

# -----------------------------
# Database configuration
# -----------------------------
# For local development, default to SQLite so you can run `python manage.py runserver`
# without needing remote DB credentials.
#
# If you want to use the remote Postgres locally, set:
#   USE_SQLITE=False
#   DB_NAME, DB_USER, DB_PASSWORD, DB_HOST, DB_PORT
#
USE_SQLITE = os.getenv("USE_SQLITE", "True" if DEBUG else "False").lower() in (
    "1", "true", "yes", "y", "on"
)

if USE_SQLITE:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": str(BASE_DIR / "db.sqlite3"),
        }
    }
else:
    _db_password = os.getenv("DB_PASSWORD", "")
    if not _db_password:
        raise RuntimeError(
            "DB_PASSWORD is not set. For local dev you can set USE_SQLITE=True, "
            "or set DB_PASSWORD (and other DB_* vars) to use Postgres."
        )

    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.getenv("DB_NAME", "db_nqljjh84al5c"),
            "USER": os.getenv("DB_USER", "db_nqljjh84al5c"),
            "PASSWORD": _db_password,
            "HOST": os.getenv("DB_HOST", "up-de-fra1-postgresql-1.db.run-on-seenode.com"),
            "PORT": os.getenv("DB_PORT", "11550"),
            "OPTIONS": {
                # Many managed Postgres providers require SSL; override locally if needed.
                "sslmode": os.getenv("DB_SSLMODE", "require"),
                "connect_timeout": int(os.getenv("DB_CONNECT_TIMEOUT", "10")),
                "keepalives": 1,
                "keepalives_idle": int(os.getenv("DB_KEEPALIVES_IDLE", "30")),
                "keepalives_interval": int(os.getenv("DB_KEEPALIVES_INTERVAL", "10")),
                "keepalives_count": int(os.getenv("DB_KEEPALIVES_COUNT", "5")),
            },
            "CONN_MAX_AGE": int(os.getenv("DB_CONN_MAX_AGE", "0")),
        }
    }



TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [ BASE_DIR / 'templates'],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "category.context_processors.menu_links"
            ],
        },
    },
]
ROOT_URLCONF = "chuefamily.urls"
WSGI_APPLICATION = "chuefamily.wsgi.application"

# Seenode runs Django behind a proxy/ingress. Tell Django how to detect HTTPS.
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
USE_X_FORWARDED_HOST = True


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases



# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

#Auth / Login
AUTH_USER_MODEL = "accounts.Account"
LOGIN_URL = "login"
LOGIN_REDIRECT_URL = "home"
LOGOUT_REDIRECT_URL = "home"

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True

LANGUAGES = [
    ("en", "English"),
    ("my", "မြန်မာ"),
]
LOCALE_PATHS = [BASE_DIR / "locale"]

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "/static/"
STATICFILES_DIRS = [
    BASE_DIR / "chuefamily" / "static",
]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')



# Cloudflare R2 (S3-compatible) Storage Configuration
#
# This project supports BOTH naming styles for env vars:
# - R2_*  (R2_ACCESS_KEY_ID, R2_SECRET_ACCESS_KEY, R2_BUCKET_NAME, R2_ENDPOINT_URL)
# - AWS_* (AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, AWS_STORAGE_BUCKET_NAME or AWS_BUCKET_NAME, AWS_S3_ENDPOINT_URL)
#
# Seenode: you can use the AWS_* names (recommended) because django-storages expects AWS_*.

USE_R2 = os.getenv("USE_R2", "False").lower() in ("1", "true", "yes", "y", "on")

if USE_R2:
    STORAGES = {
        "default": {
            "BACKEND": "storages.backends.s3.S3Storage",
        },
        "staticfiles": {
            "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
        },
    }

    # Accept either R2_* or AWS_* env var names
    AWS_ACCESS_KEY_ID = os.getenv("R2_ACCESS_KEY_ID") or os.getenv("AWS_ACCESS_KEY_ID")
    AWS_SECRET_ACCESS_KEY = os.getenv("R2_SECRET_ACCESS_KEY") or os.getenv("AWS_SECRET_ACCESS_KEY")

    AWS_STORAGE_BUCKET_NAME = (
        os.getenv("R2_BUCKET_NAME")
        or os.getenv("AWS_STORAGE_BUCKET_NAME")
        or os.getenv("AWS_BUCKET_NAME")
    )

    AWS_S3_ENDPOINT_URL = os.getenv("R2_ENDPOINT_URL") or os.getenv("AWS_S3_ENDPOINT_URL")

    # Validate required configuration early (so failures are visible in logs)
    _missing = [
        name for name, val in {
            "AWS_ACCESS_KEY_ID": AWS_ACCESS_KEY_ID,
            "AWS_SECRET_ACCESS_KEY": AWS_SECRET_ACCESS_KEY,
            "AWS_STORAGE_BUCKET_NAME": AWS_STORAGE_BUCKET_NAME,
            "AWS_S3_ENDPOINT_URL": AWS_S3_ENDPOINT_URL,
        }.items() if not val
    ]
    if _missing:
        raise RuntimeError(f"Missing required R2/S3 env var(s): {', '.join(_missing)}")

    AWS_S3_REGION_NAME = os.getenv("AWS_S3_REGION_NAME", "auto")
    AWS_S3_SIGNATURE_VERSION = "s3v4"

    # Cloudflare R2 supports path-style well; keep this explicit.
    AWS_S3_ADDRESSING_STYLE = os.getenv("AWS_S3_ADDRESSING_STYLE", "path")

    # Do not apply object ACLs (R2 uses bucket policies / public access settings).
    AWS_DEFAULT_ACL = None

    # If bucket is public, we don't need signed URLs.
    AWS_QUERYSTRING_AUTH = os.getenv("AWS_QUERYSTRING_AUTH", "False").lower() in ("1", "true", "yes", "y", "on")

    # Ensure generated URLs use https
    AWS_S3_URL_PROTOCOL = "https:"

    # Keep existing objects when uploading a file with the same name.
    AWS_S3_FILE_OVERWRITE = False

    # Upload tuning
    AWS_S3_MULTIPART_CHUNKSIZE = int(os.getenv("AWS_S3_MULTIPART_CHUNKSIZE", str(8 * 1024 * 1024)))  # 8MB
    AWS_S3_MAX_CONCURRENCY = int(os.getenv("AWS_S3_MAX_CONCURRENCY", "5"))

    # Public URL for serving media (browser-facing)
    # IMPORTANT:
    # - AWS_S3_ENDPOINT_URL is the S3 API endpoint (used for uploading).
    # - AWS_S3_CUSTOM_DOMAIN / MEDIA_URL must point to a PUBLIC URL (used for viewing).
    #
    # Set ONE of these env vars on Seenode:
    #   MEDIA_PUBLIC_BASE_URL=https://pub-xxxx.r2.dev
    #   or AWS_PUBLIC_BASE_URL=https://pub-xxxx.r2.dev
    #   or R2_PUBLIC_BASE_URL=https://pub-xxxx.r2.dev

    _public_base = (
        os.getenv("R2_PUBLIC_BASE_URL")
        or os.getenv("AWS_PUBLIC_BASE_URL")
        or os.getenv("MEDIA_PUBLIC_BASE_URL")
    )

    # django-storages generates file.url using AWS_S3_CUSTOM_DOMAIN (not MEDIA_URL).
    # So if you provide a public base URL, we also set AWS_S3_CUSTOM_DOMAIN.
    AWS_S3_CUSTOM_DOMAIN = os.getenv("AWS_S3_CUSTOM_DOMAIN")

    if not AWS_S3_CUSTOM_DOMAIN and _public_base:
        AWS_S3_CUSTOM_DOMAIN = _public_base.replace("https://", "").replace("http://", "").rstrip("/")

    if AWS_S3_CUSTOM_DOMAIN:
        MEDIA_URL = f"https://{AWS_S3_CUSTOM_DOMAIN}/"
    elif _public_base:
        MEDIA_URL = _public_base.rstrip("/") + "/"
    else:
        # Last-resort fallback (usually NOT browser-friendly)
        MEDIA_URL = AWS_S3_ENDPOINT_URL.rstrip("/") + f"/{AWS_STORAGE_BUCKET_NAME}/"

else:
    # Local development fallback
    STORAGES = {
        "default": {
            "BACKEND": "django.core.files.storage.FileSystemStorage",
        },
        "staticfiles": {
            "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
        },
    }

    MEDIA_URL = "/media/"
    MEDIA_ROOT = BASE_DIR / "media"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Global messages 
MESSAGE_TAGS= {
    messages.ERROR: 'danger',
}

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {"class": "logging.StreamHandler"},
    },
    "root": {
        "handlers": ["console"],
        "level": os.getenv("LOG_LEVEL", "INFO"),
    },
    "loggers": {
        "django.request": {
            "handlers": ["console"],
            "level": "ERROR",
            "propagate": False,
        },
    },
}

# -------------------------------------------------
# Upload limits (helps prevent connection drops when
# uploading images/products through admin)
# -------------------------------------------------
DATA_UPLOAD_MAX_MEMORY_SIZE = int(os.getenv("DATA_UPLOAD_MAX_MEMORY_SIZE", "10485760"))  # 10 MB
FILE_UPLOAD_MAX_MEMORY_SIZE = int(os.getenv("FILE_UPLOAD_MAX_MEMORY_SIZE", "10485760"))  # 10 MB

# -------------------------------------------------
# Security settings for production
# These only activate when DEBUG=False
# -------------------------------------------------
if not DEBUG:
    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_SECURE = True

    # Only enable redirect if the platform already serves HTTPS (Seenode does)
    SECURE_SSL_REDIRECT = os.getenv("SECURE_SSL_REDIRECT", "True").lower() in ("1", "true", "yes", "y", "on")

# Make sure local dev never forces HTTPS redirects
if DEBUG:
    SECURE_SSL_REDIRECT = False

"""Email configuration for account activation"""

# Use console backend in local development (prints email in terminal)
# In production you should set EMAIL_BACKEND=smtp via environment variable.
EMAIL_BACKEND = os.getenv(
    "EMAIL_BACKEND",
    "django.core.mail.backends.console.EmailBackend" if DEBUG else "django.core.mail.backends.smtp.EmailBackend",
)

DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", "no-reply@chuefamily.com")

# SMTP settings (used when EMAIL_BACKEND=smtp)
EMAIL_HOST = os.getenv("EMAIL_HOST", "smtp.gmail.com")
EMAIL_PORT = int(os.getenv("EMAIL_PORT", "587"))
EMAIL_USE_TLS = os.getenv("EMAIL_USE_TLS", "True").lower() in ("1", "true", "yes", "y", "on")

EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "")